package by.andruhovich.client.type;

public enum CommandType {
    HANDSHAKE, ACK, TIME, ECHO, EXIT, UNDEFINED_COMMAND, FILE_NOT_FOUND, START_DOWNLOAD, END_DOWNLOAD,
    CONTINUE_DOWNLOAD, NO_CONTINUE_DOWNLOAD, GET_PORT_NUMBER, ALL_PORTS_ARE_BUSY
}
